name: Build & Publish
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.8"

      - name: Install requirements and build
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller -F Steamauto.py --collect-all apprise --name Steamauto-${{ matrix.os }}

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}-dist
          path: dist

  Publish:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.PAT }}
          repository: jiajiaxd/Steamauto-Tutorial
          event-type: Sync
          
      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          path: ./Steamauto

      - name: Finalization
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "DATE=$(date +"%Y%m%d-%H%M")" >> $GITHUB_ENV
          mkdir releases
          mv Steamauto/windows-latest-dist/* releases/
          mv Steamauto/ubuntu-latest-dist/* releases/

      - name: Upload to Github Releases
        uses: ncipollo/release-action@main
        with:
          commit: "master"
          tag: ${{ env.DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: releases/*
